### ISSUE TITLE
Missing dependency to BHoM_UI in the NuGet package for net standard 2.0

### ISSUE THREAD

**Issue by adecler** [BHoM/BHoMAnalytics_Toolkit#73]
#### Description:
As per title. This causes a crash on ZCTs using the Analytics NuGet package without explicitly referencing the BHoM_UI package.
A good example of that is the BHoM API

**Comment by FraserGreenroyd** [comment]
BHoM_UI is listed as a dependency on the latest Nuget:

![image](https://github.com/BHoM/BHoMAnalytics_Toolkit/assets/18049174/3e674ea7-592e-46fd-9487-20e861f09506)

And is listed as a dependency for this repo [here](https://github.com/BHoM/BHoMAnalytics_Toolkit/blob/develop/dependencies.txt) (where the dependencies for the nuspec file are generated).

As such, I don't think there's any development actions for this repository as the dependency isn't missing at the Nuget level. I wonder if it's an issue caused by the ZCT not typically wanting `.NetFramework472` references, which BHoM_UI currently targets?

**Comment by adecler** [comment]
The image above proves that BHoM_UI is not listed as a dependency for net standard 2.0.
ZCTs are working with .Net core 6 so they will not include dependencies targeting .Net framework.
